r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)
install.packages(c('crayon', 'pbdZMQ', 'devtools'), repos='http://cran.us.r-project.org')
devtools::install_github(paste0('IRkernel/', c('repr', 'IRdisplay', 'IRkernel')))
IRkernel::installspec(prefix='/opt/medial/dist/usr', name='ir3.5.1', displayname='R 3.5.1')
install.packages('data.table')
install.packages('stringr')
install.packages('ggplot2')
install.packages('dplyr')
install.packages('plyr')
install.packages('wesanderson')
install.packages('mlr')
install.packages('xgboost')
install.packages('caret')
install.packages('gbm')
install.packages('randomForest')
install.packages('prophet')
install.packages('plotly')
install.packages('ggvis')
install.packages('DT')
install.packages('optparse')
install.packages('data.table')
